/// The swiftalk namespace: the entire public embedding API lives here —
/// `Swiftalk.eval(...)`, `Swiftalk.Interpreter`, `Swiftalk.Value`,
/// `Swiftalk.Error` — so importing the library claims exactly one
/// top-level name.
public enum Swiftalk {}

extension Swiftalk {
    /// A swiftalk runtime value, covering the SION-complete primitive
    /// space plus `Function` (Design.md §3b/§3c/§2.4). `Data` and `Date`
    /// join in later milestones.
    public enum Value: Hashable {
        case `nil`
        case bool(Bool)
        case int(Int64)
        case double(Double)
        case string(String)
        indirect case array([Value])
        indirect case dictionary([Value: Value])
        case function(FunctionObject)
        /// `Range<I>` (round 38): lazy, first-class, integer-only —
        /// `I` is Int today, BigInt someday, never Double (a deliberate
        /// divergence from Swift's versatile Range). `closed` is
        /// `a...b` vs `a..<b`.
        case range(from: Int64, to: Int64, closed: Bool)
        /// A lazy sequence (round 41): generated by
        /// `Sequence(initialState) { next }`, or derived by `map`/`filter`
        /// over one. Lazy *by default* — unlike Swift's opt-in `.lazy` —
        /// so nothing runs until iterated, `.prefix(n)`'d, or `.Array()`'d.
        case sequence(SequenceObject)
        /// A user-defined enum's case (round 45, §7): a real boxing sum —
        /// unlike the flat built-in unions (`T?`, `Primitives`).
        /// (`indirect` keeps Value's inline size small — the evaluator
        /// recurses on the Swift stack, and frame size is depth budget.)
        indirect case enumCase(EnumCaseValue)
        /// A user-defined struct's instance (round 46, §4): a COW value,
        /// consistent with the built-in collections.
        indirect case structValue(StructValue)
        /// Bytes (round 50, §3b): distinct from String — bytes are
        /// bytes, text is text. Foundation-free.
        case data([UInt8])
        /// A point in time (round 50, §3b via §3c's SION-completeness):
        /// seconds since the Unix epoch, stored as a Double — SION's own
        /// representation.
        case date(Double)
    }

    /// A user-declared struct type (§4). Identity is its equality; the
    /// language-facing type object is `constructor` (role `.structType`),
    /// and calling it IS the memberwise initializer.
    public final class StructType: Hashable {
        struct Property {
            let mutable: Bool
            let annotation: TypeAnnotation?
            let defaultExpr: Expr?
        }
        let name: String
        let propertyOrder: [String]
        let properties: [String: Property]
        /// Where the struct was declared — defaults evaluate here.
        let declEnv: Environment
        var constructor: FunctionObject?
        /// Methods and initializers (round 48). Multiple inits
        /// multi-dispatch: first declared match (arity + labels) wins,
        /// with the memberwise init as the last candidate.
        var methods: [String: FunctionObject] = [:]
        var inits: [FunctionObject] = []

        init(name: String, propertyOrder: [String],
             properties: [String: Property], declEnv: Environment) {
            self.name = name
            self.propertyOrder = propertyOrder
            self.properties = properties
            self.declEnv = declEnv
        }

        public static func == (lhs: StructType, rhs: StructType) -> Bool {
            lhs === rhs
        }
        public func hash(into hasher: inout Hasher) {
            hasher.combine(ObjectIdentifier(self))
        }
    }

    /// One struct instance: Swift's value semantics make §4's COW story
    /// free — copies are copies.
    public struct StructValue: Hashable {
        let type: StructType
        var values: [String: Value]
    }

    /// A user-declared enum type (§7). Identity is its equality; the
    /// language-facing type object is `constructor` (role `.enumType`).
    public final class EnumType: Hashable {
        let name: String
        let caseOrder: [String]
        let cases: [String: [(label: String?, typeName: String?)]]
        var constructor: FunctionObject?
        /// Methods (round 48): closure properties with `self` bound at
        /// invocation.
        var methods: [String: FunctionObject] = [:]

        init(name: String, caseOrder: [String],
             cases: [String: [(label: String?, typeName: String?)]]) {
            self.name = name
            self.caseOrder = caseOrder
            self.cases = cases
        }

        public static func == (lhs: EnumType, rhs: EnumType) -> Bool {
            lhs === rhs
        }
        public func hash(into hasher: inout Hasher) {
            hasher.combine(ObjectIdentifier(self))
        }
    }

    /// One value of a user enum: its type, its case, and the associated
    /// values. Structurally equatable and hashable (§10, synthesized).
    public struct EnumCaseValue: Hashable {
        let type: EnumType
        let caseName: String
        let associated: [Value]
    }

    /// A lazy sequence value. Identity equality, like Function.
    public final class SequenceObject: Hashable {
        enum Kind {
            /// State-machine generator: each pull calls `next` with the
            /// state elements as arguments ($0, $1, ... are entry
            /// snapshots); the returned value is the element (`nil` ends
            /// the sequence); the closure's final `$` is the next state.
            case generator(initial: [Value], next: FunctionObject)
            case mapped(SequenceObject, FunctionObject)
            case filtered(SequenceObject, FunctionObject)
        }
        let kind: Kind

        init(kind: Kind) {
            self.kind = kind
        }

        public static func == (lhs: SequenceObject, rhs: SequenceObject) -> Bool {
            lhs === rhs
        }
        public func hash(into hasher: inout Hasher) {
            hasher.combine(ObjectIdentifier(self))
        }
    }

    /// A function value: `{}` is the only function form (Design.md §2.4).
    /// Reference identity is its equality — `Function` is one collective
    /// type and functions compare as themselves, not by structure.
    /// Built-ins (`print`, ...) are the same type with a Swift closure
    /// for a body — the stdlib arrives as ordinary Function values.
    public final class FunctionObject: Hashable {
        /// What this Function stands for beyond being callable: types
        /// are constructor Functions and protocols are values too
        /// (§10, round 39).
        enum Role {
            case plain
            case type(String)
            case `protocol`(String)
            /// The `.todo` placeholder (round 44): a not-yet-implemented
            /// Function. A `let` holding it may be assigned exactly once —
            /// deferred initialization, enabling named (and mutual)
            /// recursion; calling it is an error.
            case todo
            /// A user-declared enum type (round 45): member access
            /// constructs its cases; calling it directly is an error.
            case enumType(EnumType)
            /// A user-declared struct type (round 46): calling it is the
            /// memberwise initializer.
            case structType(StructType)
        }

        let parameters: [String]      // empty means variadic (round 14)
        let body: [Stmt]
        let closure: Environment      // lexical capture
        let builtin: (([Value]) throws -> Value)?
        let role: Role

        init(parameters: [String], body: [Stmt], closure: Environment,
             builtin: (([Value]) throws -> Value)? = nil, role: Role = .plain) {
            self.parameters = parameters
            self.body = body
            self.closure = closure
            self.builtin = builtin
            self.role = role
        }

        public static func == (lhs: FunctionObject, rhs: FunctionObject) -> Bool {
            lhs === rhs
        }
        public func hash(into hasher: inout Hasher) {
            hasher.combine(ObjectIdentifier(self))
        }
    }
}

// Internal shorthands — implementation files (and @testable tests) keep
// the unqualified spellings; only the public surface is namespaced.
typealias Value = Swiftalk.Value
typealias FunctionObject = Swiftalk.FunctionObject
typealias SequenceObject = Swiftalk.SequenceObject
typealias EnumType = Swiftalk.EnumType
typealias EnumCaseValue = Swiftalk.EnumCaseValue
typealias StructType = Swiftalk.StructType
typealias StructValue = Swiftalk.StructValue

extension Value {
    /// The swiftalk type name reported by `.type` (Design.md §3).
    /// Once types become constructor Functions (§10) this will return a
    /// callable; for milestone 0 it is a name.
    public var typeName: String {
        switch self {
        case .nil:        return "Nil"
        case .bool:       return "Bool"
        case .int:        return "Int"
        case .double:     return "Double"
        case .string:     return "String"
        case .array:      return "Array"
        case .dictionary: return "Dictionary"
        case .function:   return "Function"
        case .range:      return "Range"
        case .sequence:   return "Sequence"
        case .enumCase(let ev): return ev.type.name
        case .structValue(let sv): return sv.type.name
        case .data: return "Data"
        case .date: return "Date"
        }
    }

    /// swiftalk's `.String()`: source form obeying the round-trip law
    /// `eval(x.String()) == x` (Design.md §3d). With `debug: true` it is
    /// `.debugDescription` (round 37): numbers render hexadecimal — Int
    /// as `0xff`, Double as hex-float `0x1.fep7` — for the programmer's
    /// sake, recursively through collections.
    public func sourceString(debug: Bool = false) -> String {
        switch self {
        case .nil:
            return "nil"
        case .bool(let b):
            return b ? "true" : "false"
        case .int(let i):
            return debug ? (i < 0 ? "-0x" : "0x") + String(i.magnitude, radix: 16)
                         : String(i)
        case .double(let d):
            // Swift's Double description is the shortest string that
            // round-trips, e.g. (0.1 + 0.2) -> "0.30000000000000004".
            return debug ? Value.hexFloat(d) : String(d)
        case .string(let s):
            return Value.quote(s)
        case .array(let a):
            return "[" + a.map { $0.sourceString(debug: debug) }.joined(separator: ", ") + "]"
        case .function(let f):
            // A type or protocol prints as its name — which round-trips,
            // since eval("Int") is the very same value (round 39).
            // Ordinary Function.String() as source text is OPEN (§3d);
            // until then, a non-round-tripping placeholder.
            switch f.role {
            case .type(let name), .protocol(let name):
                return name
            case .enumType(let et):
                return et.name
            case .structType(let st):
                return st.name
            case .todo:
                return ".todo"
            case .plain:
                let params = f.parameters.isEmpty ? "" : f.parameters.joined(separator: ", ") + " in "
                return "{ \(params)... }"
            }
        case .range(let lower, let upper, let closed):
            // Literal syntax — round-trips through the lexer (§3d).
            return Value.int(lower).sourceString(debug: debug)
                + (closed ? "..." : "..<")
                + Value.int(upper).sourceString(debug: debug)
        case .sequence:
            // Lazy and possibly infinite — a placeholder, like plain
            // Functions (source text is OPEN, §3d).
            return "Sequence { ... }"
        case .data(let bytes):
            // Constructor source form — round-trips (SION's base64
            // spelling is OPEN).
            return "Data([" + bytes.map {
                Value.int(Int64($0)).sourceString(debug: debug)
            }.joined(separator: ", ") + "])"
        case .date(let epoch):
            // SION's own spelling — .Date(epoch); hex-float under debug,
            // exactly as SION serializes dates.
            return ".Date(\(Value.double(epoch).sourceString(debug: debug)))"
        case .structValue(let sv):
            // Memberwise source form — round-trips wherever declared.
            return sv.type.name + "(" + sv.type.propertyOrder.map { prop in
                "\(prop): \((sv.values[prop] ?? .nil).sourceString(debug: debug))"
            }.joined(separator: ", ") + ")"
        case .enumCase(let ev):
            // Source form — round-trips wherever the enum is declared.
            var out = "\(ev.type.name).\(ev.caseName)"
            if !ev.associated.isEmpty {
                let params = ev.type.cases[ev.caseName] ?? []
                out += "(" + zip(params, ev.associated).map { param, value in
                    let v = value.sourceString(debug: debug)
                    return param.label.map { "\($0): \(v)" } ?? v
                }.joined(separator: ", ") + ")"
            }
            return out
        case .dictionary(let d):
            if d.isEmpty { return "[:]" }
            // Deterministic output: order entries by their key's source form.
            let body = d
                .map { (key: $0.key.sourceString(debug: debug), value: $0.value.sourceString(debug: debug)) }
                .sorted { $0.key < $1.key }
                .map { "\($0.key): \($0.value)" }
                .joined(separator: ", ")
            return "[" + body + "]"
        }
    }

    /// Swift-style hex-float notation (`0x1.fep7`), the Double
    /// `.debugDescription` of round 37. (The lexer does not parse
    /// hex-float literals yet — that half of the §3d round trip is OPEN.)
    static func hexFloat(_ d: Double) -> String {
        if d.isNaN { return "nan" }
        if d.isInfinite { return d < 0 ? "-inf" : "inf" }
        if d == 0 { return d.sign == .minus ? "-0x0p0" : "0x0p0" }
        let m = abs(d)
        guard m.isNormal else { return String(d) }   // subnormals: decimal fallback
        var hex = String(m.significandBitPattern, radix: 16)
        hex = String(repeating: "0", count: 13 - hex.count) + hex
        while hex.hasSuffix("0") { hex.removeLast() }
        let frac = hex.isEmpty ? "" : "." + hex
        return "\(d < 0 ? "-" : "")0x1\(frac)p\(m.exponent)"
    }

    static func quote(_ s: String) -> String {
        var out = "\""
        for scalar in s.unicodeScalars {
            switch scalar {
            case "\"":     out += "\\\""
            case "\\":     out += "\\\\"
            case "\n":     out += "\\n"
            case "\r":     out += "\\r"
            case "\t":     out += "\\t"
            case "\0":     out += "\\0"
            case let c where c.value < 0x20:
                out += "\\u{\(String(c.value, radix: 16))}"
            default:
                out.unicodeScalars.append(scalar)
            }
        }
        return out + "\""
    }
}

extension Value: CustomStringConvertible {
    public var description: String { sourceString() }
}
