/// The swiftalk namespace: the entire public embedding API lives here —
/// `Swiftalk.eval(...)`, `Swiftalk.Interpreter`, `Swiftalk.Value`,
/// `Swiftalk.Error` — so importing the library claims exactly one
/// top-level name.
public enum Swiftalk {}

extension Swiftalk {
    /// A swiftalk runtime value, covering the SION-complete primitive
    /// space plus `Function` (Design.md §3b/§3c/§2.4). `Data` and `Date`
    /// join in later milestones.
    public enum Value: Hashable {
        case `nil`
        case bool(Bool)
        case int(Int64)
        case double(Double)
        case string(String)
        indirect case array([Value])
        indirect case dictionary([Value: Value])
        case function(FunctionObject)
        /// `Range<I>` (round 38): lazy, first-class, integer-only —
        /// `I` is Int today, BigInt someday, never Double (a deliberate
        /// divergence from Swift's versatile Range). `closed` is
        /// `a...b` vs `a..<b`.
        /// `a...b` / `a..<b`; `to: nil` is the unbounded `a...` (round 88) —
        /// an infinite lazy sequence, like Swift's PartialRangeFrom.
        case range(from: Int64, to: Int64?, closed: Bool)
        /// A lazy sequence (round 41): generated by
        /// `Sequence(initialState) { next }`, or derived by `map`/`filter`
        /// over one. Lazy *by default* — unlike Swift's opt-in `.lazy` —
        /// so nothing runs until iterated, `.prefix(n)`'d, or `.Array()`'d.
        case sequence(SequenceObject)
        /// A user-defined enum's case (round 45, §7): a real boxing sum —
        /// unlike the flat built-in unions (`T?`, `Primitives`).
        /// (`indirect` keeps Value's inline size small — the evaluator
        /// recurses on the Swift stack, and frame size is depth budget.)
        indirect case enumCase(EnumCaseValue)
        /// A user-defined struct's instance (round 46, §4): a COW value,
        /// consistent with the built-in collections.
        indirect case structValue(StructValue)
        /// Bytes (round 50, §3b): distinct from String — bytes are
        /// bytes, text is text. Foundation-free.
        case data([UInt8])
        /// A point in time (round 50, §3b via §3c's SION-completeness):
        /// seconds since the Unix epoch, stored as a Double — SION's own
        /// representation.
        case date(Double)
        /// A spawned concurrent computation (round 53, §12): what
        /// `Task { ... }` / `async { ... }` returns and `await` joins.
        case task(TaskObject)
        /// A tuple (round 70): a grab bag of values, `(v0, v1, ...)` —
        /// one `Tuple` type, elements untyped, `.0`/`.1` access. Not
        /// Swift's `(T0, T1)` — deliberately loose. Labels (round 74)
        /// name positions: `(x: 1, y: 2).x`.
        indirect case tuple(TupleValue)
        /// An actor instance (round 54, §12): serialized mutable state,
        /// and swiftalk's first REFERENCE type — `let b = a` aliases.
        case actor(ActorObject)
        /// A regular expression (round 86, §11): a core type with a
        /// literal of its own, `/pattern/flags`, and the constructor
        /// `Regex(pattern)`. Wraps the stdlib's Regex; equality and
        /// hashing are by pattern and flags.
        case regex(RegexObject)
    }

    /// The compiled regex behind a `.regex` value (round 86). Flags are
    /// a subset of `imsx`, kept sorted, and applied as an inline
    /// `(?flags)` prefix — the stdlib's engine understands PCRE's.
    public final class RegexObject: Hashable {
        public let pattern: String
        public let flags: String
        let regex: Regex<AnyRegexOutput>

        init(pattern: String, flags: String) throws {
            for f in flags where !"imsx".contains(f) {
                throw SwiftalkError.syntax("unknown regex flag '\(f)' — i, m, s, x are the flags")
            }
            let sorted = String(flags.sorted())
            self.pattern = pattern
            self.flags = sorted
            do {
                regex = try Regex(sorted.isEmpty ? pattern : "(?\(sorted))" + pattern)
            } catch {
                throw SwiftalkError.syntax("invalid regex /\(pattern)/: \(error)")
            }
        }
        public static func == (lhs: RegexObject, rhs: RegexObject) -> Bool {
            lhs.pattern == rhs.pattern && lhs.flags == rhs.flags
        }
        public func hash(into hasher: inout Hasher) {
            hasher.combine(pattern)
            hasher.combine(flags)
        }
        /// `/pattern/flags` — a `/` inside the pattern escaped as `\/`,
        /// which the lexer turns back into `/` (the round-trip law).
        var sourceForm: String {
            "/" + pattern.map { $0 == "/" ? "\\/" : String($0) }.joined() + "/" + flags
        }
    }

    /// A tuple's contents (round 74): values with optional labels. A
    /// tuple is a rigid Array of arguments, so it IS a collection of
    /// its values; labels are cosmetic — equality and hashing ignore
    /// them (`(x: 1, y: 2) == (1, 2)`).
    public struct TupleValue: Hashable, RandomAccessCollection, MutableCollection {
        var values: [Value]
        var labels: [String?]

        init(values: [Value], labels: [String?]? = nil) {
            self.values = values
            self.labels = labels ?? Array(repeating: nil, count: values.count)
        }

        public var startIndex: Int { values.startIndex }
        public var endIndex: Int { values.endIndex }
        public func index(after i: Int) -> Int { i + 1 }
        public func index(before i: Int) -> Int { i - 1 }
        public subscript(position: Int) -> Value {
            get { values[position] }
            set { values[position] = newValue }
        }
        /// The position a label names, if any.
        func index(ofLabel label: String) -> Int? {
            labels.firstIndex(of: label)
        }

        public static func == (lhs: TupleValue, rhs: TupleValue) -> Bool {
            lhs.values == rhs.values
        }
        public func hash(into hasher: inout Hasher) {
            hasher.combine(values)
        }
    }

    /// A stored property's observers, runnable (round 58b): built at
    /// declaration, closed over the declaring environment.
    struct PropertyObservers {
        let will: FunctionObject?
        let did: FunctionObject?
    }

    /// A computed property (round 57): a getter that runs on read —
    /// the paren-less read builtins always had (`.count`) — and an
    /// optional setter that runs on assignment (`newValue` bound, or a
    /// custom name via `set(v)`).
    struct ComputedProperty {
        let annotation: TypeAnnotation?
        let get: FunctionObject
        let set: FunctionObject?
    }

    /// A user-declared struct type (§4). Identity is its equality; the
    /// language-facing type object is `constructor` (role `.structType`),
    /// and calling it IS the memberwise initializer.
    public final class StructType: Hashable {
        struct Property {
            let mutable: Bool
            let annotation: TypeAnnotation?
            let defaultExpr: Expr?
            /// Observer bodies as parsed (round 58b): `.function`
            /// exprs — willSet's parameter is the incoming value
            /// (`newValue` or custom), didSet's the replaced one
            /// (`oldValue` or custom). Stored properties only.
            var willSetExpr: Expr? = nil
            var didSetExpr: Expr? = nil
        }
        let name: String
        let propertyOrder: [String]
        let properties: [String: Property]
        /// Where the struct was declared — defaults evaluate here.
        let declEnv: Environment
        var constructor: FunctionObject?
        /// Methods and initializers (round 48). Multiple inits
        /// multi-dispatch: first declared match (arity + labels) wins,
        /// with the memberwise init as the last candidate.
        var methods: [String: FunctionObject] = [:]
        var inits: [FunctionObject] = []
        /// Computed properties (round 57): read runs `get`, assignment
        /// runs `set` — the value-semantics write-back still applies.
        var computed: [String: ComputedProperty] = [:]
        /// Stored-property observers (round 58b), keyed by property.
        var observers: [String: PropertyObservers] = [:]

        init(name: String, propertyOrder: [String],
             properties: [String: Property], declEnv: Environment) {
            self.name = name
            self.propertyOrder = propertyOrder
            self.properties = properties
            self.declEnv = declEnv
        }

        public static func == (lhs: StructType, rhs: StructType) -> Bool {
            lhs === rhs
        }
        public func hash(into hasher: inout Hasher) {
            hasher.combine(ObjectIdentifier(self))
        }
    }

    /// One struct instance: Swift's value semantics make §4's COW story
    /// free — copies are copies.
    public struct StructValue: Hashable {
        let type: StructType
        var values: [String: Value]
    }

    /// A user-declared enum type (§7). Identity is its equality; the
    /// language-facing type object is `constructor` (role `.enumType`).
    public final class EnumType: Hashable {
        let name: String
        let caseOrder: [String]
        let cases: [String: [(label: String?, typeName: String?)]]
        var constructor: FunctionObject?
        /// Methods (round 48): closure properties with `self` bound at
        /// invocation.
        var methods: [String: FunctionObject] = [:]

        init(name: String, caseOrder: [String],
             cases: [String: [(label: String?, typeName: String?)]]) {
            self.name = name
            self.caseOrder = caseOrder
            self.cases = cases
        }

        public static func == (lhs: EnumType, rhs: EnumType) -> Bool {
            lhs === rhs
        }
        public func hash(into hasher: inout Hasher) {
            hasher.combine(ObjectIdentifier(self))
        }
    }

    /// One value of a user enum: its type, its case, and the associated
    /// values. Structurally equatable and hashable (§10, synthesized).
    public struct EnumCaseValue: Hashable {
        let type: EnumType
        let caseName: String
        let associated: [Value]
    }

    /// A lazy sequence value. Identity equality, like Function.
    public final class SequenceObject: Hashable {
        enum Kind {
            /// State-machine generator: each pull calls `next` with the
            /// state elements as arguments ($0, $1, ... are entry
            /// snapshots); the returned value is the element (`nil` ends
            /// the sequence); the closure's final `$` is the next state.
            case generator(initial: [Value], next: FunctionObject)
            /// Coroutine-backed (round 52): `Sequence(f)` — each pull
            /// resumes the body, each `yield` emits an element, and
            /// returning ends the sequence.
            case coroutine(body: FunctionObject)
            case mapped(SequenceObject, FunctionObject)
            case filtered(SequenceObject, FunctionObject)
            /// `.enumerated()` (round 73): (index, element) tuples, lazily.
            case enumerated(SequenceObject)
            /// The unbounded range `a...` as a lazy base (round 88), so
            /// its `map`/`filter`/`enumerated`/`prefix { }` defer.
            case counting(from: Int64)
            /// `.prefix { } { }` / `.dropFirst { } { }` (round 88), lazily.
            case takenWhile(SequenceObject, FunctionObject)
            case droppedWhile(SequenceObject, FunctionObject)
            /// `.dropFirst(n)` (round 89), lazily — the only one of the
            /// slicing family that need not see the end.
            case dropped(SequenceObject, Int)
        }
        let kind: Kind

        init(kind: Kind) {
            self.kind = kind
        }

        public static func == (lhs: SequenceObject, rhs: SequenceObject) -> Bool {
            lhs === rhs
        }
        public func hash(into hasher: inout Hasher) {
            hasher.combine(ObjectIdentifier(self))
        }
    }

    /// A function value: `{}` is the only function form (Design.md §2.4).
    /// Reference identity is its equality — `Function` is one collective
    /// type and functions compare as themselves, not by structure.
    /// Built-ins (`print`, ...) are the same type with a Swift closure
    /// for a body — the stdlib arrives as ordinary Function values.
    public final class FunctionObject: Hashable {
        /// What this Function stands for beyond being callable: types
        /// are constructor Functions and protocols are values too
        /// (§10, round 39).
        enum Role {
            case plain
            case type(String)
            case `protocol`(String)
            /// The `.todo` placeholder (round 44): a not-yet-implemented
            /// Function. A `let` holding it may be assigned exactly once —
            /// deferred initialization, enabling named (and mutual)
            /// recursion; calling it is an error.
            case todo
            /// A user-declared enum type (round 45): member access
            /// constructs its cases; calling it directly is an error.
            case enumType(EnumType)
            /// A user-declared struct type (round 46): calling it is the
            /// memberwise initializer.
            case structType(StructType)
            /// A user-declared actor type (round 54): calling it
            /// constructs an instance — a reference.
            case actorType(ActorType)
        }

        let parameters: [String]      // empty means variadic (round 14)
        let body: [Stmt]
        let closure: Environment      // lexical capture
        let builtin: (([Value]) throws -> Value)?
        let role: Role

        init(parameters: [String], body: [Stmt], closure: Environment,
             builtin: (([Value]) throws -> Value)? = nil, role: Role = .plain) {
            self.parameters = parameters
            self.body = body
            self.closure = closure
            self.builtin = builtin
            self.role = role
        }

        public static func == (lhs: FunctionObject, rhs: FunctionObject) -> Bool {
            lhs === rhs
        }
        public func hash(into hasher: inout Hasher) {
            hasher.combine(ObjectIdentifier(self))
        }
    }
}

// Internal shorthands — implementation files (and @testable tests) keep
// the unqualified spellings; only the public surface is namespaced.
typealias Value = Swiftalk.Value
typealias FunctionObject = Swiftalk.FunctionObject
typealias SequenceObject = Swiftalk.SequenceObject
typealias EnumType = Swiftalk.EnumType
typealias EnumCaseValue = Swiftalk.EnumCaseValue
typealias StructType = Swiftalk.StructType
typealias StructValue = Swiftalk.StructValue
typealias TaskObject = Swiftalk.TaskObject
typealias TupleValue = Swiftalk.TupleValue
typealias RegexObject = Swiftalk.RegexObject

extension Swiftalk.Value {
    /// An unlabeled tuple from values — the common construction.
    static func tuple(_ values: [Value]) -> Value {
        .tuple(TupleValue(values: values))
    }
    /// A labeled tuple (round 74).
    static func tuple(_ values: [Value], labels: [String?]) -> Value {
        .tuple(TupleValue(values: values, labels: labels))
    }
}
typealias ActorType = Swiftalk.ActorType
typealias ActorObject = Swiftalk.ActorObject
typealias ComputedProperty = Swiftalk.ComputedProperty
typealias PropertyObservers = Swiftalk.PropertyObservers

extension Value {
    /// The swiftalk type name reported by `.type` (Design.md §3).
    /// Once types become constructor Functions (§10) this will return a
    /// callable; for milestone 0 it is a name.
    public var typeName: String {
        switch self {
        case .nil:        return "Nil"
        case .bool:       return "Bool"
        case .int:        return "Int"
        case .double:     return "Double"
        case .string:     return "String"
        case .array:      return "Array"
        case .dictionary: return "Dictionary"
        case .function:   return "Function"
        case .range:      return "Range"
        case .sequence:   return "Sequence"
        case .enumCase(let ev): return ev.type.name
        case .structValue(let sv): return sv.type.name
        case .data: return "Data"
        case .date: return "Date"
        case .task: return "Task"
        case .tuple: return "Tuple"
        case .actor(let obj): return obj.type.name
        case .regex: return "Regex"
        }
    }

    /// swiftalk's `.String()`: source form obeying the round-trip law
    /// `eval(x.String()) == x` (Design.md §3d). With `debug: true` it is
    /// `.debugDescription` (round 37): numbers render hexadecimal — Int
    /// as `0xff`, Double as hex-float `0x1.fep7` — for the programmer's
    /// sake, recursively through collections.
    public func sourceString(debug: Bool = false) -> String {
        sourceString(debug: debug, seen: [])
    }

    /// The worker: `seen` carries the reference objects already being
    /// printed on this path, so a cyclic graph (possible since round
    /// 55's class references — a.next = b; b.next = a) elides instead
    /// of recursing forever.
    private func sourceString(debug: Bool, seen: Set<ObjectIdentifier>) -> String {
        switch self {
        case .nil:
            return "nil"
        case .bool(let b):
            return b ? "true" : "false"
        case .int(let i):
            return debug ? (i < 0 ? "-0x" : "0x") + String(i.magnitude, radix: 16)
                         : String(i)
        case .double(let d):
            // Swift's Double description is the shortest string that
            // round-trips, e.g. (0.1 + 0.2) -> "0.30000000000000004".
            return debug ? Value.hexFloat(d) : String(d)
        case .string(let s):
            return Value.quote(s)
        case .array(let a):
            return "[" + a.map { $0.sourceString(debug: debug, seen: seen) }.joined(separator: ", ") + "]"
        case .function(let f):
            // A type or protocol prints as its name — which round-trips,
            // since eval("Int") is the very same value (round 39).
            // Ordinary Function.String() as source text is OPEN (§3d);
            // until then, a non-round-tripping placeholder.
            switch f.role {
            case .type(let name), .protocol(let name):
                return name
            case .enumType(let et):
                return et.name
            case .structType(let st):
                return st.name
            case .actorType(let at):
                return at.name
            case .todo:
                return ".todo"
            case .plain:
                let params = f.parameters.isEmpty ? "" : f.parameters.joined(separator: ", ") + " in "
                return "{ \(params)... }"
            }
        case .range(let lower, let upper, let closed):
            // Literal syntax — round-trips through the lexer (§3d);
            // the unbounded `a...` prints as written (round 88).
            guard let upper else {
                return Value.int(lower).sourceString(debug: debug, seen: seen) + "..."
            }
            return Value.int(lower).sourceString(debug: debug, seen: seen)
                + (closed ? "..." : "..<")
                + Value.int(upper).sourceString(debug: debug, seen: seen)
        case .sequence:
            // Lazy and possibly infinite — a placeholder, like plain
            // Functions (source text is OPEN, §3d).
            return "Sequence { ... }"
        case .task:
            // A live computation — a placeholder, like Functions.
            return "Task { ... }"
        case .tuple(let t):
            // Literal syntax — round-trips; an unlabeled 1-tuple spells
            // `(x,)`, a labeled one `(x: 1)` (round 74).
            let body = zip(t.labels, t.values).map { label, value in
                (label.map { "\($0): " } ?? "") + value.sourceString(debug: debug, seen: seen)
            }.joined(separator: ", ")
            let lonely = t.count == 1 && t.labels[0] == nil
            return "(" + body + (lonely ? ",)" : ")")
        case .actor(let obj):
            // A reference: identity can never round-trip (a re-entered
            // spelling would be a NEW actor), so a placeholder in the
            // Function family — but an informative one, showing state.
            // A reference already on this print path elides — a cycle
            // must not print forever.
            guard !seen.contains(ObjectIdentifier(obj)) else {
                return "\(obj.type.name) { ... }"
            }
            var seen = seen
            seen.insert(ObjectIdentifier(obj))
            let props = obj.type.propertyOrder.map {
                "\($0): \((obj.storage[$0] ?? .nil).sourceString(debug: debug, seen: seen))"
            }.joined(separator: ", ")
            return props.isEmpty ? "\(obj.type.name) { }" : "\(obj.type.name) { \(props) }"
        case .data(let bytes):
            // SION's own spelling since round 97 — .Data("base64"), which
            // re-enters as Data(base64); the debug form keeps the bytes
            // visible, in hex, through the Array constructor.
            if debug {
                return "Data([" + bytes.map {
                    Value.int(Int64($0)).sourceString(debug: true, seen: seen)
                }.joined(separator: ", ") + "])"
            }
            return ".Data(\"\(Base64.encode(bytes))\")"
        case .date(let epoch):
            // SION's own spelling — .Date(epoch); hex-float under debug,
            // exactly as SION serializes dates.
            return ".Date(\(Value.double(epoch).sourceString(debug: debug, seen: seen)))"
        case .regex(let r):
            return r.sourceForm              // /pattern/flags — a literal, re-enters
        case .structValue(let sv):
            // Memberwise source form — round-trips wherever declared.
            return sv.type.name + "(" + sv.type.propertyOrder.map { prop in
                "\(prop): \((sv.values[prop] ?? .nil).sourceString(debug: debug, seen: seen))"
            }.joined(separator: ", ") + ")"
        case .enumCase(let ev):
            // Source form — round-trips wherever the enum is declared.
            var out = "\(ev.type.name).\(ev.caseName)"
            if !ev.associated.isEmpty {
                let params = ev.type.cases[ev.caseName] ?? []
                out += "(" + zip(params, ev.associated).map { param, value in
                    let v = value.sourceString(debug: debug, seen: seen)
                    return param.label.map { "\($0): \(v)" } ?? v
                }.joined(separator: ", ") + ")"
            }
            return out
        case .dictionary(let d):
            if d.isEmpty { return "[:]" }
            // Deterministic output: order entries by their key's source form.
            let body = d
                .map { (key: $0.key.sourceString(debug: debug, seen: seen), value: $0.value.sourceString(debug: debug, seen: seen)) }
                .sorted { $0.key < $1.key }
                .map { "\($0.key): \($0.value)" }
                .joined(separator: ", ")
            return "[" + body + "]"
        }
    }

    /// Swift-style hex-float notation (`0x1.fep7`), the Double
    /// `.debugDescription` of round 37. (The lexer does not parse
    /// hex-float literals yet — that half of the §3d round trip is OPEN.)
    static func hexFloat(_ d: Double) -> String {
        if d.isNaN { return "nan" }
        if d.isInfinite { return d < 0 ? "-inf" : "inf" }
        if d == 0 { return d.sign == .minus ? "-0x0p0" : "0x0p0" }
        let m = abs(d)
        guard m.isNormal else { return String(d) }   // subnormals: decimal fallback
        var hex = String(m.significandBitPattern, radix: 16)
        hex = String(repeating: "0", count: 13 - hex.count) + hex
        while hex.hasSuffix("0") { hex.removeLast() }
        let frac = hex.isEmpty ? "" : "." + hex
        return "\(d < 0 ? "-" : "")0x1\(frac)p\(m.exponent)"
    }

    static func quote(_ s: String) -> String {
        var out = "\""
        for scalar in s.unicodeScalars {
            switch scalar {
            case "\"":     out += "\\\""
            case "\\":     out += "\\\\"
            case "\n":     out += "\\n"
            case "\r":     out += "\\r"
            case "\t":     out += "\\t"
            case "\0":     out += "\\0"
            case let c where c.value < 0x20:
                out += "\\u{\(String(c.value, radix: 16))}"
            default:
                out.unicodeScalars.append(scalar)
            }
        }
        return out + "\""
    }
}

extension Value: CustomStringConvertible {
    public var description: String { sourceString() }
}
